### ISSUE TITLE
cannot compile missing some files.

### ISSUE THREAD

**Issue by JianwenSun** [6A/Cometary#13]
![image](https://user-images.githubusercontent.com/8909264/28834786-e5f892d2-7715-11e7-9010-e5d15e6b5d3e.png)

**Comment by 6A** [comment]
Hey man, and thanks for your interest. However the project has shifted to the [`analyzer`](https://github.com/6A/Cometary/tree/analyzer) branch, on which I'm working heavily.

For the matter, it looks like you're trying to compile the `IL` sample, which is outdated. I'm truly sorry, but right now the only answer I can give you is "wait for the next release."
